export const VIETNAM_BANKS = [
  'Vietcombank (VCB)',
  'VietinBank (CTG)',
  'BIDV',
  'Agribank (VBA)',
  'Techcombank (TCB)',
  'MBBank (MB)',
  'VPBank (VPB)',
  'ACB',
  'Sacombank (STB)',
  'TPBank (TPB)',
  'HDBank (HDB)',
  'VIB',
  'SHB',
  'SeABank (SSB)',
  'MSB',
  'OCB',
  'LPBank (LPB)',
  'Eximbank (EIB)',
  'Nam A Bank (NAB)',
  'VietABank (VAB)',
  'Kienlongbank (KLB)',
  'BaoVietBank (BVB)'
];
